name: ci.yml
on:
  push:
    branches:
      - main

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Send mail
        uses: ./
        id: mail
        with:
          api_key: ${{ secrets.MAILGUN_API_KEY }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          from: ${{ secrets.MAILGUN_FROM }}
          to: ${{ secrets.MAILGUN_TO }}
          subject: ${{ github.event.head_commit.message }}
          message: '<p>Hello World</p>'
      - name: Print outputs
        run: echo ${{ steps.mail.outputs.result }}
